default: &default
  adapter: postgresql
  database: jsonb_accessor
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>

test:
  <<: *default
